
services:
  postgres:
    image: postgres:18rc1
    pull_policy: always
    restart: no
    ports:
      - 5432:5432
    shm_size: 128m
    env_file :
      - .env
    volumes:
      - my_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  keycloak:
    container_name: keycloak_2
    image: quay.io/keycloak/keycloak:26.4
    pull_policy: always
    restart: no
    ports:
      - 8080:8080
    env_file :
      - .env
    volumes:
      # Themes customizados
      - ./my-themes:/opt/keycloak/themes
    command: [
      "start", 
      "--spi-theme-cache-themes=false",
      "--spi-theme-cache-templates=false",
      "--spi-theme-static-max-age=-1",
      "--http-port=8080", 
      "--http-enabled=true",
      "--hostname-strict=false",
      "--hostname-debug=true",
      "--health-enabled=true",
      "--verbose",
      "--db=postgres",
      "--db-url=jdbc:postgresql://postgres:5432/$${DB_POSTGRES_SPACE}",
      "--db-password=$${DB_POSTGRES_PASSWORD}",
      "--db-username=$${DB_POSTGRES_USER}",
    ]
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # UI
    restart: unless-stopped

volumes:
  my_postgres_data:
