
services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    depends_on:
      - api
      - web
      - mongo
      - keycloak
    volumes:
      # Main nginx config
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apps/nginx/certs:/etc/nginx/certs:ro

  web:
    image: web
    container_name: web
    ports:
      - "5173:5173"
    volumes:
      - ./apps/web:/app/apps/web
      - /app/apps/web/node_modules
    env_file:
      - ./apps/web/.env.dev
    restart: unless-stopped

  api:
    image: api
    container_name: api
    build:
      context: .
      dockerfile: apps/api/dockerfile
    ports:
      - "5002:5002"
    env_file:
      - ./apps/api/.env
      - ./apps/api/.env.dev
    restart: unless-stopped
    volumes:
      - ./apps/api:/app/apps/api
      - /app/apps/api/node_modules
    depends_on:
      mongo:
        condition: service_healthy
        restart: true
  
  postgres:
    image: postgres:18rc1
    pull_policy: always
    restart: no
    ports:
      - 5432:5432
    shm_size: 128m
    env_file :
      - ./apps/authentication/.env
    volumes:
      - my_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  keycloak:
    container_name: keycloak_2
    image: quay.io/keycloak/keycloak:26.4
    pull_policy: always
    restart: no
    ports:
      - 8080:8080
    env_file :
      - ./apps/authentication/.env
      - ./apps/authentication/.env.dev
    volumes:
      # Themes customizados
      - ./apps/authentication/my-themes:/opt/keycloak/themes
      - ./apps/authentication/realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: [
      "start-dev", 
      "--spi-theme-cache-themes=false",
      "--spi-theme-cache-templates=false",
      "--spi-theme-static-max-age=-1",
      "--http-port=8080", 
      "--hostname-debug=true",
      "--health-enabled=true",
      "--verbose",
      "--db=postgres",
      "--db-url=jdbc:postgresql://postgres:5432/$${DB_POSTGRES_SPACE}",
      "--db-password=$${DB_POSTGRES_PASSWORD}",
      "--db-username=$${DB_POSTGRES_USER}",
      "--import-realm",
    ]
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # UI
    restart: unless-stopped

  mongo:
    image: mongo:8.0.14-noble
    pull_policy: always
    restart: no
    ports:
      - 27017:27017
    env_file:
      - ./apps/api/.env
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --quiet --authenticationDatabase admin --username $${MONGO_INITDB_ROOT_USERNAME} --password $${MONGO_INITDB_ROOT_PASSWORD} localhost:27017/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s 

volumes:
  my_postgres_data:
  mongodb_data:
